# Cirrus CI configuration
# https://cirrus-ci.com/github/libexif/exif

task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      # There isn't a stable 13.0 image yet (2019-10)
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-0
      # The stable 11.3 image causes "Agent is not responding" so use a snapshot
      image_family: freebsd-11-3-snap
      image_family: freebsd-10-4

  env:
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKE_FLAGS: -j 2

  pkginstall_script:
    - pkg install -y autoconf automake libtool gettext-tools gettext-runtime popt pkgconf git
    - git clone --depth=1 https://github.com/libexif/libexif.git /tmp/libexif
  builddeps_script:
    - (cd /tmp/libexif && autoreconf -sivf && ./configure --prefix=/tmp/libexif/install && make V=1 && make V=1 install)
  configure_script:
    - autoreconf -sivf
    - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" PKG_CONFIG_PATH="/tmp/libexif/install/lib/pkgconfig:/usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig" POPT_CFLAGS="$(pkg-config --cflags popt)"  POPT_LIBS="$(pkg-config --libs popt)" || { tail -300 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check || { tail -300 test/test-suite.log; false; }
  install_script:
    - make V=1 install
