# Travis CI configuration file

sudo: false

language: c

git:
  depth: 1

# Install needed packages on Ubuntu (OS X is done with brew below)
addons:
  apt:
    packages:
    - autopoint
    - libpopt-dev

env:
  # More configurations are configured in the matrix section
  matrix:
    - CONFIG=normal
    - CONFIG=c90
    - CONFIG=stackprotect
  global:
    - MAKEFLAGS='-j 2'

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-6.0
          - ubuntu-toolchain-r-test
        packages:
          - autopoint
          - clang-6.0
          - libpopt-dev
    compiler: clang
    env:
      - CONFIG=clang6
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - autopoint
          - g++-8
          - libpopt-dev
    compiler: gcc
    env:
      - CONFIG=gcc8
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-6.0
          - ubuntu-toolchain-r-test
        packages:
          - autopoint
          - clang-6.0
          - libtool
    compiler: clang
    cache:
      directories:
        - $HOME/popt
    # Required for -fsanitize=undefined
    # see https://github.com/travis-ci/travis-ci/issues/9033
    sudo: required
    env:
      - CONFIG=sanitize
  - os: linux
    addons:
      apt:
        packages:
          - autopoint
          - libpopt-dev
          - subversion
    compiler: gcc
    env:
      - CONFIG=coverage

install:
# Install and build the latest libexif
  - |
    if [ "$CONFIG" != "coverage" ] ; then
      cd "$HOME"
      # OS X has a weird alias that causes cd to abort with set -e so leave it
      # off when it's run.
      set -e
      git clone --depth=1 https://github.com/libexif/libexif.git
      set +e
      cd libexif
      set -e
      PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
      ./configure --prefix="${HOME}"
      make
      make install
      set +e
      cd "$TRAVIS_BUILD_DIR"
    fi
# Install libpopt on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install popt; fi
# libpopt0:1.16-8ubuntu1 has a memory leak that causes UBSAN to fail. Build
# a fixed version to use when running those tests.
  - |
    if [ "$CONFIG" = "sanitize" -a ! -e "$HOME/popt/lib/libpopt.a" ] ; then
      set -e
      cd "$HOME"
      curl --fail -OL http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/p/popt/popt_1.16-11.debian.tar.xz -OL http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/p/popt/popt_1.16.orig.tar.gz -OL http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/p/popt/popt_1.16-11.dsc
      dpkg-source -x popt_1.16-11.dsc
      cd popt-1.16
      sed -i -e 's/\(AM_GNU_GETTEXT_VERSION\)/dnl \1/' configure.ac
      autoreconf -sivf
      ./configure --prefix="${HOME}/popt" --disable-nls --disable-shared
      make
      make install
      cd "$TRAVIS_BUILD_DIR"
      set +e
    fi
  - |
    if [ "$CONFIG" = "coverage" ] ; then
      set -e
      pip install --user cpp-coveralls
      cd "$HOME"
      git clone --depth=1 https://github.com/libexif/libexif-testsuite.git
      cd libexif-testsuite
      mkdir src
      ln -s "$TRAVIS_BUILD_DIR" src/exif
      ./build-config.sh
      autoreconf -sivf
      set +e
    fi

script:
  # Ensure brew gettext is in the PATH so autopoint is found on OS X
  - PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
  - if [ "$CONFIG" = "normal" ] ; then CFLAGS='-Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "c90" ] ; then CFLAGS='-std=iso9899:1990 -D_XOPEN_SOURCE=500 -Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "stackprotect" ] ; then CFLAGS='-g -O0 -fstack-protector-all'; fi
  - if [ "$CONFIG" = "clang6" ] ; then CFLAGS='-Wall -Wextra -O3'; export CC=clang-6.0; fi
  - if [ "$CONFIG" = "gcc8" ] ; then CFLAGS='-Wall -Wextra -O3'; export export CC=gcc-8; fi
  - if [ "$CONFIG" = "sanitize" ] ; then CFLAGS='-g -Wall -Wextra -fsanitize=address -fsanitize=undefined'; export CC=clang-6.0; CONFIGURE_OPTS="POPT_CFLAGS=-I${HOME}/popt/include POPT_LIBS=-lpopt LDFLAGS=-L${HOME}/popt/lib"; fi
  - if [ "$CONFIG" = "coverage" ] ; then cd "$HOME"/libexif-testsuite; CFLAGS=--coverage; CONFIGURE_OPTS='LDFLAGS=--coverage'; export MAKEFLAGS='-j 1'; fi
  - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" PKG_CONFIG_PATH="${HOME}/lib/pkgconfig" $CONFIGURE_OPTS || { tail -300 config.log; false; }
  - make
  - make check || { tail -300 test/test-suite.log; false; }
  - make install
  - if [ "$CONFIG" = "coverage" ] ; then cd "$TRAVIS_BUILD_DIR"; fi

after_success:
  - if [ "$CONFIG" = "coverage" ] ; then coveralls --exclude test --gcov-options '\-lp'; fi
