# Travis CI configuration file

sudo: false

language: c

# Install needed packages on Ubuntu (OS X is done with brew below)
addons:
  apt:
    packages:
    - autopoint
    - libpopt-dev

install:
# Install and build the latest libexif
  - git clone --depth=1 https://github.com/libexif/libexif.git
  - (cd libexif && PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf && ./configure --prefix="${HOME}" && make install)
# Install libpopt on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install popt; fi

script:
  # Ensure brew gettext is in the PATH so autopoint is found on OS X
  - PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
  - ./configure --prefix="${HOME}" PKG_CONFIG_PATH="${HOME}/lib/pkgconfig"
  - make
  - make check
  - make install

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
